language: csharp
mono: latest
os:
  - osx
  - linux
script:
  - sudo ./build.sh
git:
  submodules: false
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo nuget update -self; fi
cache:
  directories:
    - Source/packages