language: csharp
script:
  - sudo ./build.sh --target=$TARGET --$SCRIPTARGS
os: osx
matrix:
  include:
    - dotnet: 2.1.502
      env: TARGET=TestCore SCRIPTARGS=
    - mono: 5.18.1
      env: TARGET=Test SCRIPTARGS=
git:
  submodules: false
cache:
  directories:
    - Source/packages