version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2019
- Ubuntu
environment:
  matrix:
  - Target: TestCore
    ScriptArgs: '--netcoreVersion="3.1.200"'
  - Target: TestCore
    ScriptArgs: '--netcore="netcoreapp2.1" --netcoreVersion="2.2.100"'
  - Target: Test
    ScriptArgs: ''
matrix:
  exclude:
  - image: Visual Studio 2017
    Target: TestCore
    ScriptArgs: '--netcoreVersion="3.1.200"'
  - image: Visual Studio 2017
    Target: Test
  - image: Visual Studio 2019
    Target: TestCore
    ScriptArgs: '--netcore="netcoreapp2.1" --netcoreVersion="2.2.100"'
  - image: Ubuntu
    Target: TestCore
    ScriptArgs: '--netcore="netcoreapp2.1" --netcoreVersion="2.2.100"'
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1 -Target %Target% -ScriptArgs '%ScriptArgs%'
- sh: ./build.sh -t --target=$Target $ScriptArgs
test: off
